### ISSUE TITLE
Phone Numbers and emails cannot be mixed in input

### ISSUE THREAD

**Issue by ryanbmilbourne** [yuha0/applechecker#1]
When I give input as:

``` bash
./stock.py <model> <zip> "2138675309,myemail@gmail.com" 10 <creds>
```

...I get the following stacktrace:

```
./stock.py MNPR2LL/A "99999" "1234567890,snip@gmail.com" 30 "snip@gmail.com" "snip"
09/19/2016 23:07:11 start tracking MNPR2LL/A in 99999. Alert will sent to 1234567890,snip@gmail.com
Traceback (most recent call last):
  File "./stock.py", line 80, in <module>
    check_stock(*sys.argv[1:])
  File "./stock.py", line 16, in check_stock
    my_alert.send(initmsg)
  File "./stock.py", line 72, in send_email
    mailer.sendmail(self.login, self.dest, message)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/smtplib.py", line 742, in sendmail
    raise SMTPRecipientsRefused(senderrs)
smtplib.SMTPRecipientsRefused: {'1234567890,snip@gmail.com': (553, '5.1.2 The recipient address <12345667890> is not a valid RFC-5321 address. nb13sm35674925pab.43 - gsmtp')}
```

Are you accepting PRs? If so, I can submit a fix sometime tomorrow.

**Comment by yuha0** [comment]
@ryanbmilbourne Yeah, feel free. PRs are welcome.

**Comment by yuha0** [comment]
Alert class has been separated from the main script and now users have complete control over how they want to be alerted.
